### ISSUE TITLE
How your's module build docker image?

### ISSUE THREAD

**Issue by nguyenviettuananh** [justinram11/serverless-aws-batch#15]
Hi @justinram11,
My serverless application implement "serverless-aws-batch" and my application "MUST" have node_modules that's i defined in package-lock.json yarn.lock.
But i confuse that's your plugin COPY my "node_modules" folder to zip file then build and upload to ECR or your plugin installed my node_modules through "yarn" or "npm"?
Because i have problem between my local machine and my batch computed engine. If i invoke local lambda function it's work really well, but it's unexpected when i invoke function that's trigger aws batch on my computed engine
My Local Machine:
OS: MAC OSX 10.15
Node: 12.18.1
NPM: 6.14.5
Localstack: serverless local implemetation [https://hub.docker.com/r/localstack/localstack](url)
Please give me some advice.
Many thanks

**Comment by justinram11** [comment]
Hey @nguyenviettuananh ,

Thanks for the interest in the project! To give a little background on what the plugin does:

The serverless framework itself is responsible for packaging all of your code and your dependencies (node_modules) into a ".zip" file at `.serverless/<project-name>.zip` when you run `sls package` or `sls deploy`.

This plugin then copies that `.serverless/<project-name>.zip` file to the docker image and extracts it.

So first thing to check would be to make sure that `node_modules` _is_ located inside of your `.zip` file. If it is not, then my best guess would be that you have some sort of configuration error in your `serverless.yaml` file that is excluding it (and the configuration issue is with serverless itself, and not this plugin): https://stackoverflow.com/questions/46417182/serverless-not-including-my-node-modules

I'd explicitly set it under your includes:
```
package:
  include:
    - node_modules/**
```

Thanks! Please let me know if that resolves your issue

**Comment by nguyenviettuananh** [comment]
> Hey @nguyenviettuananh ,
> 
> Thanks for the interest in the project! To give a little background on what the plugin does:
> 
> The serverless framework itself is responsible for packaging all of your code and your dependencies (node_modules) into a ".zip" file at `.serverless/<project-name>.zip` when you run `sls package` or `sls deploy`.
> 
> This plugin then copies that `.serverless/<project-name>.zip` file to the docker image and extracts it.
> 
> So first thing to check would be to make sure that `node_modules` _is_ located inside of your `.zip` file. If it is not, then my best guess would be that you have some sort of configuration error in your `serverless.yaml` file that is excluding it (and the configuration issue is with serverless itself, and not this plugin): https://stackoverflow.com/questions/46417182/serverless-not-including-my-node-modules
> 
> I'd explicitly set it under your includes:
> 
> ```
> package:
>   include:
>     - node_modules/**
> ```
> 
> Thanks! Please let me know if that resolves your issue

Thanks for fast reply @justinram11,
I just wanna confirm that's my hypothesis was right.
So any kind of workaround solution that i can install my node_modules in docker before zip my code folder?
Or should i fork your code and workaround some kind 👍

**Comment by justinram11** [comment]
Oh I think I understand now -- you have some sort of native node_module that is getting compiled for MacOS and then doesn't work when running on the Linux docker image?

The python solution for this is to actually install the dependencies onto a separate docker image, and them copy them over into the `.zip` with the `serverless-python-requirements` plugin, but I'm not actually sure that something exists for NodeJS (I've mostly worked with python to be honest).

So two things that would be good to try would be:
* See if there is any other plugin that will generate the `.zip` file via a separate docker image that runs the yarn install inside the docker image (That's got to be a problem for regular lambda functions too? It is on python)
* Otherwise you can try using this to insert additional commands into the docker image (such as installing custom yarn packages). You can see how the additional commands get inserted into the docker image at `lib/docker.js:77`

serverless.yml
```
custom:
  awsBatch:
    additionalDockerRunCommands:
      - npm install -g <package>
```

(Not sure if npm is installed on the image at the point in the docker install -- you might need to install it first)
