### ISSUE TITLE
Have some errors running it

### ISSUE THREAD

**Issue by mwawrusch** [justinram11/serverless-aws-batch#6]
First of all thanks for sharing this. 
I am trying to set up an instance but ran into a few problems:
1. the docker image wasn't found, I had to change that to this one: https://hub.docker.com/r/lambci/lambda/

2. I run into this error (regardless if I use EC2 or SPOT):

```
An error occurred: IamRoleBatchSpotFleetManagement - Policy arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 83b41812-b420-4312-8c48-f2080ee1d917).
```

Not sure what to do about that.

Thanks

**Comment by justinram11** [comment]
Hey @mwawrusch ,

Thanks for checking the project out!

It looks like AWS deprecated the `AmazonEC2SpotFleetRole` role. I've updated it to be the correct role so things should now be working in v1.0.4.

It also looks like docker archived my repositories since I hadn't logged in for awhile (grr). They look to be back online now -- so I'd recommend changing them back to the original justinram11 docker image. Otherwise I think that you'll run into issues trying to get IAM permissions to your batch jobs.

Please let me know if you're still running into issues!

**Comment by mwawrusch** [comment]
Thanks, very much appreciated!!!
