### ISSUE TITLE
The repository with name 'YYYY' does not exist in the registry with id 'XXXX'

### ISSUE THREAD

**Issue by lskrajny** [justinram11/serverless-aws-batch#7]
Tested on serverless 1.67.0 

Seems like the docker image is trying to be pushed before ECR repository is created in cloudformation.

Serverless: Logging into ECR...
Serverless: Uploading to ECR...
The push refers to repository [XXXX.dkr.ecr.eu-central-1.amazonaws.com/YYY]
91e896bb3bd6: Preparing 
0e698354cfab: Preparing 
ac77572d5230: Preparing 
c12294a45f16: Preparing 
name unknown: The repository with name 'YYYY' does not exist in the registry with id 'XXXX'
 
  Error --------------------------------------------------
 
  Error: null
      at dockerCommand (/Users/test/node_modules/serverless-aws-batch/lib/docker.js:41:15)
      at ServerlessAWSBatch.pushDockerImageToECR (/Users/test/node_modules/serverless-aws-batch/lib/docker.js:114:5)
      at ServerlessAWSBatch.tryCatcher (/Users/test/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/test/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/test/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/Users/test/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/Users/test/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/Users/test/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/test/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/test/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (timers.js:637:19)
      at process.topLevelDomainCallback (domain.js:126:23)

**Comment by justinram11** [comment]
Hey @Iskrajny ,

Thanks for checking the package out -- sorry you're having issues running it!

Can I ask you to confirm if you're seeing the ECR repository in your CloudFormation stack and if when viewing "View Push Commands" from the ECR console it matches the url in `XXXX.dkr.ecr.eu-central-1.amazonaws.com/YYY`?

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/47002419/81359129-ebe2dc80-909d-11ea-9b45-b53d1da1e9c2.png">

![image](https://user-images.githubusercontent.com/47002419/81359296-5dbb2600-909e-11ea-9b5f-0306535b0d20.png)

AFAIK the serverless framework does a "create stack" with an initial set of resource (S3 bucket, ECR Repository, etc) and then later does an "update stack" and package upload -- so I'm not initially seeing how we could be trying to push to the repo before it's created (since it's part of that initial "create stack" request):

```
    this.hooks = {
      'after:package:initialize': () => BbPromise.bind(this)
        .then(generateCoreTemplate.generateCoreTemplate), // Creates ECR Repository

      'before:package:compileFunctions': () => BbPromise.bind(this)
        .then(batchenvironment.validateAWSBatchServerlessConfig)
        .then(batchenvironment.generateAWSBatchTemplate)
        .then(batchtask.compileBatchTasks),

      'after:package:createDeploymentArtifacts': () => BbPromise.bind(this)
        .then(docker.buildDockerImage),

      'before:aws:deploy:deploy:uploadArtifacts': () => BbPromise.bind(this)
        .then(docker.pushDockerImageToECR),

      'before:remove:remove': () => BbPromise.bind(this)
        .then(awscli.deleteAllDockerImagesInECR)
    }
```

**Comment by justinram11** [comment]
Actually, it looks like @gcaliene ran into this issue as well: https://github.com/gcaliene/serverless-aws-batch/commit/3845bdb8f9530cdc82a3578e1db5f74eea5f696a

It looks like it might be related to different hook order-of-operations in the latest version of serverless (I'm stuck on 1.60.5 due to: https://github.com/UnitedIncome/serverless-python-requirements/issues/449)

I've updated it to the hook that he had selected, and was able to successfully deploy with Serverless 1.70.0, and Node 12.16.3

Please let me know if you're still experiencing issues in v1.0.4 and what version of serverless, node, and platform you're using -- Thanks!

**Comment by nexeh** [comment]
@justinram11 Looks like (https://github.com/UnitedIncome/serverless-python-requirements/issues/449https://github.com/UnitedIncome/serverless-python-requirements/issues/449) is still a issue. ive been blocked by this forever as well. Im curious if you made any progress on getting around that issue?

**Comment by gvijay370** [comment]
is this issue fixed??? plz let me know.

**Comment by 1024gs** [comment]
I'm facing the same issue.

I used the "[Deploy to Amazon ECS](https://github.com/actions/starter-workflows/blob/main/deployments/aws.yml)" workflow template.
I deleted the lines from 80 onwards and replaced the [AWS_REGION](https://github.com/actions/starter-workflows/blob/dfc0cdc56b16efd9727aa420b4942723e48d065b/deployments/aws.yml#L34) and [ECR_REPOSITORY](https://github.com/actions/starter-workflows/blob/dfc0cdc56b16efd9727aa420b4942723e48d065b/deployments/aws.yml#L35) variables.

All the steps seem to run successfully but the [docker-push](https://github.com/actions/starter-workflows/blob/dfc0cdc56b16efd9727aa420b4942723e48d065b/deployments/aws.yml#L77) step fails with the following error: 

**name unknown: The repository with name 'public.ecr.aws/a1e6v7a9/myrepo' does not exist in the registry with id 'xxx'**
**Error**: Process completed with exit code 1.

P.S. The repository exists and I can push to it from my localhost.
